<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');

$colorbox = Mage::helper('colorbox');

// Sizes
$popupsize = explode(',', $colorbox->getPopupSize());
$mainsize = explode(',', $colorbox->getMainSize());
$thumbsize = explode(',', $colorbox->getThumbSize());
?>

<?php if (Mage::getStoreConfig('colorbox/settings/jquery') == 'google'): ?>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<?php endif; ?>
<?php if (Mage::getStoreConfig('colorbox/settings/jquery') == 'local'): ?>
	<script src="<?php echo $this->getSkinUrl('magmodules/colorbox/jquery.min.js'); ?>"></script>
<?php endif; ?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
	<p class="product-image product-image-zoom">
		<?php
		$_img = '<img id="image" src="' . $this->helper('catalog/image')->init($_product, 'image') . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
		echo $_helper->productAttribute($_product, $_img, 'image');
		?>
	</p>
	<p class="zoom-notice"
	   id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
	<div class="zoom">
		<img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>"
			 alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>"
			 class="btn-zoom-out"/>
		<div id="track">
			<div id="handle"></div>
		</div>
		<img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>"
			 alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in"/>
	</div>

	<script src="<?php echo $this->getSkinUrl('magmodules/colorbox/jquery.colorbox-min.js'); ?>"
			type="text/javascript"></script>
	<link rel="stylesheet"
		  href="<?php echo $this->getSkinUrl('magmodules/colorbox/' . Mage::getStoreConfig('colorbox/theme/theme') . '/colorbox.css'); ?>"
		  type="text/css" media="screen"/>
	<script>
		jQuery.noConflict();
		jQuery(document).ready(function () {
			jQuery(".colorbox").colorbox(
				{
					rel: 'colorbox',
					current: "<?php echo Mage::helper('colorbox')->__('Bild {current} von {total}') ?>",
					previous: "<?php echo Mage::helper('colorbox')->__('previous') ?>",
					next: "<?php echo Mage::helper('colorbox')->__('next') ?>",
					close: "<?php echo Mage::helper('colorbox')->__('close') ?>",
					transition: "<?php echo Mage::getStoreConfig('colorbox/theme/transition') ?>",
					speed: "<?php echo Mage::getStoreConfig('colorbox/theme/transition_speed') ?>"
				}
			);
		});
	</script>

<?php else: ?>
	<p class="product-image">
		<a id="productimagemain" class="colorbox"
		   href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->keepFrame(false)->resize($popupsize[0], $popupsize[1]); ?>">
			<?php
			$_img = '<img src="' . $this->helper('catalog/image')->init($_product, 'image')->resize(265) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
			echo $_helper->productAttribute($_product, $_img, 'image');
			?>
		</a>
	</p>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0): ?>
	<div class="more-views">
		<h2><?php echo $this->__('More Views') ?></h2>
		<ul class="product-image-thumbs">
			<?php $i = 0;
			foreach ($this->getGalleryImages() as $_image): ?>
				<?php if ($this->isGalleryImageVisible($_image)): ?>
					<li>
						<!-- 2017-01-02 SP ersetzt durch "neu"
						<a class="colorbox cboxElement"
						   href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(false)->resize($popupsize[0], $popupsize[1]); ?>"
						   title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
							<img
								src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(false)->resize($thumbsize[0], $thumbsize[1]); ?>"
								alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
						</a>
						-->
						<!-- 2017-01-02 SP "neu" Bildtitle und "Alttext" jetzt Produktname -->
						<a class="colorbox cboxElement"
						   href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(false)->resize($popupsize[0], $popupsize[1]); ?>"
						   title="">
							<img
								src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->keepFrame(false)->resize($thumbsize[0], $thumbsize[1]); ?>"
								alt="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"/>
						</a>
					</li>
				<?php endif; ?>
			<?php $i++; endforeach; ?>
		</ul></div>
	<?php endif; ?>
