<?php
/**
 * @var $this FireGento_MageSetup_Block_Checkout_Agreements
 */

/** @var $helper FireGento_MageSetup_Helper_Data */
$helper = Mage::helper('magesetup');
$agreements = $this -> getAgreements ();

?>

<form action="" id="checkout-agreements" onsubmit="return false;">
	<!-- SDZeCOM_Aurednink Bestelltyp -->
	<input type="hidden"
		id="<?php echo SDZeCOM_Aurednik_Helper_Product :: ORDER_TYPE_FIELD; ?>"
		name="<?php echo SDZeCOM_Aurednik_Helper_Product :: ORDER_TYPE_FIELD; ?>">

	<!-- SDZeCOM_Aurednink Betellkommentar -->
	<textarea type="text"
		id="<?php echo SDZeCOM_Aurednik_Helper_Product :: ORDER_COMMENT_FIELD; ?>"
		name="<?php echo SDZeCOM_Aurednik_Helper_Product :: ORDER_COMMENT_FIELD; ?>"></textarea>
	<ol class="checkout-agreements">
	
<?php foreach ($agreements as $agreement): ?>	
  
    	<li>
			<p class="agree">
            <?php if($agreement->getIsRequired()): ?>
                <input type="checkbox"
					id="agreement-<?php echo $agreement->getId()?>"
					name="agreement[<?php echo $agreement->getId()?>]" value="1"
					title="<?php echo $this->htmlEscape($agreement->getCheckboxText()) ?>"
					class="checkbox" />
            <?php endif; ?>
            <label <?php if($agreement->getIsRequired()): ?>
					for="agreement-<?php echo $agreement->getId()?>" <?php endif; ?>><?php echo $agreement->getIsHtml() ? $agreement->getCheckboxText() : $this->escapeHtml($agreement->getCheckboxText()) ?></label>
				<a href="<?php echo $helper->getAgreementUrl($agreement) ?>"
					onclick="window.open(this.href, '', 'width=600,height=600,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes').focus(); return false;"><?php echo $this->__('[Show]') ?></a>
			</p>
		</li>
<?php endforeach ?>

<!-- Wenn Produkthinweise existieren --> 
<?php $objOrderWarningNotices = $this -> getOrdertWarningsNoticesAgreements (); ?>

<?php if ( $this -> hasOrderWarningNotices () && $objOrderWarningNotices !== FALSE ) : ?>

	<?php foreach ( $objOrderWarningNotices as $agreement ) : ?>	
	    	<li>
				<p class="agree">
	            <?php if($agreement->getIsRequired()): ?>
	                <input type="checkbox"
						id="agreement-<?php echo $agreement->getId()?>"
						name="agreement[<?php echo $agreement->getId()?>]" value="1"
						title="<?php echo $this->htmlEscape($agreement->getCheckboxText()) ?>"
						class="checkbox" />
	            <?php endif; ?>
	            <label <?php if($agreement->getIsRequired()): ?>
						for="agreement-<?php echo $agreement->getId()?>" <?php endif; ?>><?php echo $agreement->getIsHtml() ? $agreement->getCheckboxText() : $this->escapeHtml($agreement->getCheckboxText()) ?></label>
					<a href="<?php echo $helper->getAgreementUrl($agreement) ?>"
						onclick="window.open(this.href, '', 'width=600,height=600,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes').focus(); return false;"><?php echo $this->__('[Show]') ?></a>
				</p>
			</li>
	<?php endforeach ?>
<?php endif;?>	
</ol>
</form>